// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnCqLajdro8tUi6peYJyDrJkGenTUxqjs',
    appId: '1:488140763242:web:64785e77b714767de5da13',
    messagingSenderId: '488140763242',
    projectId: 'mi-kiosco-f5f9b',
    authDomain: 'mi-kiosco-f5f9b.firebaseapp.com',
    storageBucket: 'mi-kiosco-f5f9b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1KOJQ6hpazvHPO7cy0L8pFPhU52PjVyo',
    appId: '1:488140763242:android:233793b142962281e5da13',
    messagingSenderId: '488140763242',
    projectId: 'mi-kiosco-f5f9b',
    storageBucket: 'mi-kiosco-f5f9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIcGlthH1Uxet8AKjjxGfBuymF8WTTz9o',
    appId: '1:488140763242:ios:4cc0cf1c940d20b2e5da13',
    messagingSenderId: '488140763242',
    projectId: 'mi-kiosco-f5f9b',
    storageBucket: 'mi-kiosco-f5f9b.firebasestorage.app',
    iosBundleId: 'com.example.kioscoStockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIcGlthH1Uxet8AKjjxGfBuymF8WTTz9o',
    appId: '1:488140763242:ios:4cc0cf1c940d20b2e5da13',
    messagingSenderId: '488140763242',
    projectId: 'mi-kiosco-f5f9b',
    storageBucket: 'mi-kiosco-f5f9b.firebasestorage.app',
    iosBundleId: 'com.example.kioscoStockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnCqLajdro8tUi6peYJyDrJkGenTUxqjs',
    appId: '1:488140763242:web:71bf0dc0be39df7de5da13',
    messagingSenderId: '488140763242',
    projectId: 'mi-kiosco-f5f9b',
    authDomain: 'mi-kiosco-f5f9b.firebaseapp.com',
    storageBucket: 'mi-kiosco-f5f9b.firebasestorage.app',
  );
}
